# Generated by Django 3.2.8 on 2021-11-07 17:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100, unique=True)),
                ('CostPerUnit', models.IntegerField()),
                ('Quantity', models.IntegerField()),
                ('SellingPrice', models.IntegerField()),
            ],
        ),
    ]
