# Generated by Django 3.2.8 on 2021-11-07 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_po_ps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='po',
            name='Product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product', unique=True),
        ),
    ]
