# Generated by Django 3.2.8 on 2021-11-07 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_po_product'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='po',
            unique_together={('Order', 'Product')},
        ),
    ]
