# Generated by Django 3.2.8 on 2021-11-07 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_po_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='DatePlaced',
            field=models.DateTimeField(unique=True),
        ),
    ]
